# Ref: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Only - (dash) character is allowed for bullet lists.
MD004:
  style: dash

MD013:
  # No line length requirement for general text.
  line_length: -1
  # For code, match Ozone's line length.
  code_block_line_length: 120
  # Shorter headings keep the minimap on the right legible.
  heading_block_line_length: 80

# Numbered lists must use numbers in ascending order.
MD029:
  style: ordered

# Disallow inline html except for these allowed elements.
MD033:
  allowed_elements:
  - br
  - Tabs
  - TabItem

# Allow bare URLs since wrapping URLs in <> is invalid mdx.
MD034: false

# Horiziontal rule.
MD035:
  style: ---

MD044:
  # Do not enforced capitalization checks inside code blocks or HTML.
  # This feature makes markdownlint better at enforcing capitalization than cspell.
  code_blocks: false
  html_elements: false
  # Enforce consistent capitalization for these words:
  names:
  # Ozone components:
  - OM
  - Ozone Manager
  - SCM
  - Storage Container Manager
  - Recon
  - Datanode
  - Datanodes
  - S3 Gateway
  - HDDS
  # Acronyms:
  - FSO
  - OBS
  - ofs
  - HttpFS
  - CLI
  - RPC
  - EC
  - SPNEGO
  - SASL
  - TLS
  - mTLS
  - SSL
  - X.509
  - REST API
  # Other systems:
  - gRPC
  - RocksDB
  - Jira
  - Java
  - Maven
  - GPG
  - Netty
  - Docker Compose
  - Docker
  - pnpm
  - S3
  - Hadoop
  # Enforce capitalization for these words only when they are used in sentences (surrounded by spaces).
  # Other uses in repo names or links like [apache/ozone](https://github.com/apache/ozone) are ok.
  - " Ratis "
  - " Ozone "
  - " Apache "
  - " ASF "
  - " HTTP "
  - " HTTPS "

# Indentation should not be used to inidcate a multi-line code block.
MD046:
  style: fenced

# Only allow ``` to define multi-line code blocks.
MD048:
  style: backtick

MD054:
  # Disable inline links with the same URL, like [www.example.com](www.example.com)
  url_inline: false

# Use pipes on either end of every line in a table.
MD055:
  style: leading_and_trailing
