version: "3"

services:
  site:
    build: "."
    image: "ozone-site-dev"
    ports:
      - "3000:3000"
    volumes:
      - ".:/ozone-site"
    working_dir: "/ozone-site"
    command: ["npm", "run", "start"]