version: "3"

services:
  site:
    build: "."
    image: "ozone-site-dev"
    ports:
      - "3000:3000"
    volumes:
      - ".:/ozone-site"
    working_dir: "/ozone-site"
    # ERROR: Docusaurus dev server is available within the container (curl localhost:3000 in the container),
    #   but not outside of the container from the web browser.
    # ERROR: Does not use node_modules directory specified in the config.
    #   Possible to fix with https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder?
    command: sh -c "pnpm config set modules-dir /ozone-site-deps/node_modules && pnpm start"
