name: static

on:
  workflow_call:

concurrency:
  group: static-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  script_dir: .github/scripts
  node_version: 20

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Check license headers
      uses: apache/skywalking-eyes@v0.5.0
  spelling:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Enable corepack
      run: |
        corepack enable
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
        cache: pnpm
    - name: Install pnpm dependencies
      run: pnpm install --dev
    - name: Run Spell Check
      working-directory: ${{ env.script_dir }}
      run: |
        ./spelling.sh
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Run yamllint
      working-directory: ${{ env.script_dir }}
      run: |
        ./yamllint.sh
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Enable corepack
      run: |
        corepack enable
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
        cache: pnpm
    - name: Install pnpm dependencies
      run: pnpm install --dev
    - name: Run markdownlint
      working-directory: ${{ env.script_dir }}
      run: |
        ./markdownlint.sh
  frontmatter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Enable corepack
      run: |
        corepack enable
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
        cache: pnpm
    - name: Install pnpm dependencies
      run: pnpm install --dev
    - name: Run markdown frontmatter check
      working-directory: ${{ env.script_dir }}
      run: |
        ./frontmatter.sh
  sidebar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Enable corepack
      run: |
        corepack enable
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
        cache: pnpm
    - name: Install pnpm dependencies
      run: pnpm install --dev
    - name: Run docs sidebar check
      working-directory: ${{ env.script_dir }}
      run: |
        ./sidebar.sh
  file-names:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Run file name check
      working-directory: ${{ env.script_dir }}
      run: |
        ./names.sh
